name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/raw-to-jpeg

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/raw-to-jpeg:latest
            ${{ secrets.DOCKER_USERNAME }}/raw-to-jpeg:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Verify Build Success
        run: |
          echo "Docker image pushed to Docker Hub:"
          echo " - Image: ${{ secrets.DOCKER_USERNAME }}/raw-to-jpeg:latest"
          echo " - Commit SHA Tag: ${{ github.sha }}"
