name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Python Dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt
          pip install unittest-xml-reporting

      - name: Run Unit Tests
        run: |
          python -m unittest discover -s . -p "test_*.py"

  build-and-publish:
    name: Build and Publish Docker Image
    needs: run-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/raw-to-jpeg

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/raw-to-jpeg:latest
            ${{ secrets.DOCKER_USERNAME }}/raw-to-jpeg:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Verify Build Success
        run: |
          echo "Docker image pushed to Docker Hub:"
          echo " - Image: ${{ secrets.DOCKER_USERNAME }}/raw-to-jpeg:latest"
          echo " - Commit SHA Tag: ${{ github.sha }}"
